/* screenio: screen capture, cursor state and input injection.
 * All functions are synchronous. They return SIO_OK or a negative SIO_E_* code.
 * C ABI 1.0: see "C ABI" in README.md for what later versions may and may not change. */

#ifndef SCREENIO_H
#define SCREENIO_H

/* Generated by cbindgen from crates/screenio/src/lib.rs; edit that file and run scripts/header.sh. */

#include <stddef.h>
#include <stdint.h>

#define SIO_OK 0

// No new frame within the timeout.
#define SIO_E_TIMEOUT -1

// The capture target changed; reopen the capturer.
#define SIO_E_RESET -2

// A missing OS permission.
#define SIO_E_PERMISSION -3

// Not implemented on this platform.
#define SIO_E_UNSUPPORTED -4

// A bad argument.
#define SIO_E_INVALID -5

// An OS call failed.
#define SIO_E_OS -6

// An internal error.
#define SIO_E_PANIC -7

#define SIO_FORMAT_BGRA 0

// Flags for `sio_input_key_scancode`: an E0-prefixed scancode.
#define SIO_KEY_EXTENDED 1

// An E1-prefixed scancode.
#define SIO_KEY_EXTENDED1 2

// A key release; without it the event is a press.
#define SIO_KEY_RELEASE 4

// Lock key flags for `sio_input_sync_locks`, as in RDP's TS_SYNC_EVENT.
#define SIO_LOCK_SCROLL 1

#define SIO_LOCK_NUM 2

#define SIO_LOCK_CAPS 4

#define SIO_LOCK_KANA 8

// Buttons for `sio_input_mouse_button`.
#define SIO_BUTTON_LEFT 0

#define SIO_BUTTON_RIGHT 1

#define SIO_BUTTON_MIDDLE 2

#define SIO_BUTTON_X1 3

#define SIO_BUTTON_X2 4

// Panes for `sio_open_privacy_settings`.
#define SIO_PANE_SCREEN_RECORDING 0

#define SIO_PANE_ACCESSIBILITY 1

typedef struct sio_capture_t sio_capture_t;

typedef struct sio_input_t sio_input_t;

typedef struct sio_virtual_display_t sio_virtual_display_t;

typedef struct sio_display_t {
  uint32_t id;
  // Origin in virtual-desktop coordinates.
  int32_t x;
  int32_t y;
  // Size in captured pixels.
  uint32_t width;
  uint32_t height;
  // Captured pixels per coordinate unit.
  float scale;
  uint8_t primary;
  char name[64];
  // 1 for the stand-in display macOS keeps when no screen is attached.
  uint8_t placeholder;
} sio_display_t;

typedef struct sio_frame_t {
  // Valid until the next `sio_capture_frame` on the same handle, or `sio_capture_close`.
  const uint8_t *data;
  uint32_t width;
  uint32_t height;
  // Bytes per row.
  uint32_t stride;
  // `SIO_FORMAT_*`.
  uint32_t format;
} sio_frame_t;

typedef struct sio_cursor_shape_t {
  // Changes whenever the shape changes.
  uint64_t id;
  uint32_t width;
  uint32_t height;
  int32_t hot_x;
  int32_t hot_y;
  // `width * height * 4` bytes, owned by the library; release with `sio_cursor_shape_free`.
  uint8_t *rgba;
  size_t rgba_len;
  // Bitmap pixels per point.
  float scale;
} sio_cursor_shape_t;

typedef struct sio_session_info_t {
  uint8_t can_capture;
  uint8_t can_inject;
  char backend[32];
} sio_session_info_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// The library version as 0xMMmmpp: 0x010000 is 1.0.0.
uint32_t sio_version(void);

const char *sio_strerror(int32_t err);

// Fills up to `cap` entries and always stores the total number of displays in `count`.
int32_t sio_display_list(struct sio_display_t *out, uint32_t cap, uint32_t *count);

// 1 when this system can create virtual displays, 0 otherwise.
int32_t sio_virtual_display_supported(void);

// Creates a display that exists only in software (macOS: the private CGVirtualDisplay API,
// checked at run time), `width` x `height` pixels at 1x, named `name` (UTF-8). On a Mac without
// a screen it replaces the placeholder and becomes the desktop.
int32_t sio_virtual_display_create(const char *name,
                                   uint32_t width,
                                   uint32_t height,
                                   struct sio_virtual_display_t **out);

// The display id for `sio_display_list` and `sio_capture_open`; 0 for a null handle.
uint32_t sio_virtual_display_id(const struct sio_virtual_display_t *display);

// Waits until the display shows the new size. Returns `SIO_E_OS` when macOS settles on another
// size instead (3840x2160 ends at 1920x1080 until macOS has learned that size for the display,
// for example from a switch in System Settings); the display then keeps that size.
int32_t sio_virtual_display_resize(struct sio_virtual_display_t *display,
                                   uint32_t width,
                                   uint32_t height);

// Removes the display; on a Mac without a screen the placeholder comes back.
void sio_virtual_display_destroy(struct sio_virtual_display_t *display);

int32_t sio_capture_open(uint32_t display_id, struct sio_capture_t **out);

// Like `sio_capture_open`, but the frames are scaled to `width` x `height`.
int32_t sio_capture_open_scaled(uint32_t display_id,
                                uint32_t width,
                                uint32_t height,
                                struct sio_capture_t **out);

// Waits up to `timeout_ms` for a frame that differs from the last one returned. `SIO_E_RESET`
// means the capture stream stopped (display change and the like): close and reopen.
int32_t sio_capture_frame(struct sio_capture_t *cap, uint32_t timeout_ms, struct sio_frame_t *out);

void sio_capture_close(struct sio_capture_t *cap);

int32_t sio_cursor_position(int32_t *x, int32_t *y, uint8_t *visible);

int32_t sio_cursor_shape(struct sio_cursor_shape_t *out);

void sio_cursor_shape_free(struct sio_cursor_shape_t *shape);

int32_t sio_input_open(struct sio_input_t **out);

int32_t sio_input_mouse_move(struct sio_input_t *input, int32_t x, int32_t y);

int32_t sio_input_mouse_move_rel(struct sio_input_t *input, int32_t dx, int32_t dy);

// `button` is one of `SIO_BUTTON_*`.
int32_t sio_input_mouse_button(struct sio_input_t *input, uint32_t button, uint8_t down);

// 120 per notch; positive is up or right.
int32_t sio_input_mouse_wheel(struct sio_input_t *input, int32_t dx, int32_t dy);

// A set-1 scancode; `flags` combines `SIO_KEY_*`.
int32_t sio_input_key_scancode(struct sio_input_t *input, uint16_t set1_code, uint32_t flags);

int32_t sio_input_key_unicode(struct sio_input_t *input, uint32_t codepoint, uint8_t down);

// `lock_flags` combines `SIO_LOCK_*` for the lock keys that should be on.
int32_t sio_input_sync_locks(struct sio_input_t *input, uint32_t lock_flags);

int32_t sio_input_release_all(struct sio_input_t *input);

void sio_input_close(struct sio_input_t *input);

int32_t sio_session_info(struct sio_session_info_t *out);

int32_t sio_session_request_permissions(struct sio_session_info_t *out);

// Opens the System Settings pane where the user switches a permission on.
int32_t sio_open_privacy_settings(uint32_t pane);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SCREENIO_H */
